config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
    end
  end

  resources :companies
  root 'pages#home'

  get 'terms', to: 'pages#terms'
  get 'map', to: 'pages#map'
  get 'admin', to: 'pages#admin'

  resources :jobs do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
      put "like" => "jobs#like"
    end
  end
  get "my_jobs", to: 'jobs#my_jobs', as: :my_jobs
  get 'tags/:tag', to: 'jobs#index', as: :tag

  devise_for :users
end

app/models/job.rb
class Job < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_title, against: :title

  pg_search_scope :search_job,
                  against: [:title, :description, :job_author, :location],
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }

  # TAGS
  acts_as_taggable_on :tags
  ActsAsTaggableOn.delimiter = ' '
  ActsAsTaggableOn.force_lowercase = true

  # LIKE / UNLIKE / VOTABLE
  acts_as_votable

  # Job Views / Impressions
  is_impressionable

  has_many_attached :images, service: :amazon
  has_one_attached :company_logo, service: :amazon
  has_rich_text :description
  belongs_to :user

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  validates :title,
            :url,
            :apply_url,
            :description,
            :job_type,
            :location,
            :job_author,
            :industry,
            :start_date,
            :status,
            :num_employees,
            :salary_range,
            :status, :presence => true

  # JOB CONSTANTS
  TYPES = [
    "Full-Time",
    "Part-Time",
    "Contract",
    "Freelance",
    "Internship",
    "Temporary",
    "Comission",
    "Volunteer",
    "Casual",
    "Apprenticeship"
  ]
  STATUS = [
    "Active",
    "Archived"
  ]
  SALARY_RANGE = [
    "$20,000 - $50,000",
    "$50,000 - $75,000",
    "$75,000 - $90,000",
    "$90,000 - $110,000",
    "$110,000 - $150,000",
    "$150,000 - $200,000",
    "$200,000 +"
  ]
  INDUSTRIES = [
    "Advertising",
    "Agriculture",
    "Communications",
    "Construction",
    "Creative",
    "Education",
    "Entertainment",
    "Farming",
    "Fashion",
    "Finance",
    "Green",
    "Heavy",
    "Hospitality",
    "Information",
    "Information Technology",
    "Infrastructure",
    "Light",
    "Manufacturing",
    "Materials",
    "Media",
    "Music",
    "Publishing",
    "Retail",
    "Robotics",
    "Service",
    "Space",
    "Technology",
    "Telecom"
  ]
  NUM_EMPLOYEES = [
    "1 - 10",
    "10 - 50",
    "50 - 200",
    "200 - 1,000",
    "1,000 - 10,000",
    "10,000 +"
  ]
  BENEFITS = [
    "Extended Health Care",
    "Dental Care",
    "Vision Care",
    "RRSP Match",
    "Unlimited Paid Time Off (UPTO)",
    "Casual Dress",
    "Life Insurance",
    "Disability Insurance",
    "Flexible Schedule",
    "Company Pension",
    "On-site Parking",
    "Work From Home",
    "Discounted or Free Food",
    "Wellness Program",
    "Profit Sharing",
    "Company Events",
    "On-site Gym",
    "Company Car",
    "Tuition Reimbursement",
    "Stock Options",
    "On-site Childcare",
    "Employee Assistance Program",
    "Commuter Benefits",
    "Employee Stock Purchase Plan",
    "Store Discount",
    "None"
  ]

  # Geolocation of the jobs - For the map
  def coordinates
    [longitude, latitude]
  end

  # Geolocation of the jobs - For the map
  def to_feature
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": coordinates
      },
      "properties": {
        "job_id": id,
        "title": title,
        "description": description,
        "website": url,
        "apply_url": apply_url,
        "job_type": job_type,
        "location": location,
        "job_author": job_author,
        "remote": remote_ok,
        "salary_range": salary_range,
        "start_date": start_date,
        "info_window": ApplicationController.new.render_to_string(
          partial: "jobs/infowindow",
          locals: { job: self }
        )
      }
    }
  end

  def most_used_tags
    ActsAsTaggableOn::Tag.most_used(10)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy delete_upload like ]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :js, :html, :json

#  Attach payment to all features

  def index
    if params[:search]
      @jobs = Job.search_job(params[:search])
    elsif params[:tag]
      @jobs = Job.tagged_with(params[:tag])
    else
      @jobs = Job.all.limit(10).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end
    @tags = ActsAsTaggableOn::Tag.most_used(10).order("created_at DESC")
  end

  def my_jobs
    @user = current_user
    @my_jobs = current_user.jobs
  end

  def show
    @related_jobs = @job.find_related_tags
    @geojson = build_geojson
    
    
    impressionist(@job)
  end

  def new
    @user = current_user
    @job = @user.jobs.new
  end

  def edit
  end

  def create
    @user = current_user
    @job = @user.jobs.new(job_params)

    # STRIPE PAYMENTS
    # token = params[:stripeToken]
    # job_type = params[:job_type]
    # job_title = params[:title]
    # card_brand = params[:user][:card_brand]
    # card_exp_month = params[:user][:card_exp_month]
    # card_exp_year = params[:user][:card_exp_year]
    # card_last4 = params[:user][:card_last4]
    #
    # charge = Stripe::Charge.create(
    #   :amount => 0,
    #   :currency => "usd",
    #   :description => job_type,
    #   :statement_descriptor => job_title,
    #   :source => token
    # )
    #
    # current_user.stripe_id = charge.id
    # current_user.card_brand = card_brand
    # current_user.card_expiry_month = card_exp_month
    # current_user.card_expiry_year = card_exp_year
    # current_user.card_last4 = card_last4
    # current_user.save!


    respond_to do |format|
      if @job.save
        format.html { render :show, notice: "Your job listing was purchased successfully." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end

    # rescue Stripe::CardError => e
    #   flash.alert = e.message
    #   render action: :new


  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def delete_upload
    attachments = ActiveStorage::Attachment.where(id: params[:upload_id])
    attachments.map(&:purge)
    redirect_to edit_job_path(@job), notice: 'Image deleted.'
  end

  def like
    if current_user.voted_for? @job
      @job.unliked_by(current_user)
    else
      @job.liked_by(current_user)
    end
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title,
                                  :description,
                                  :url,
                                  :job_type,
                                  :location,
                                  :job_author,
                                  :remote_ok,
                                  :apply_url,
                                  :salary_range,
                                  :start_date,
                                  :industry,
                                  :search,
                                  :tag_list,
                                  :company_logo,
                                  :num_employees,
                                  :status,
                                  benefits: [],
                                  images: [])
    end

    def build_geojson
      @job_feature = [@job]
      {
        type: "FeatureCollection",
        features: @job_feature.map(&:to_feature)
      }
    end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, html: { multipart: true }, local: true do |form| %>
  <div class="row">
    <div class="col"></div>
    <div class="col-md-10">
      <% if @job.errors.any? %>
        <% @job.errors.full_messages.each do |message|%>
          <h3><%= message %> </h3>
        <%end%>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
  <div class="row m-4">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title"><%= action_name.capitalize %> Job</h2>
          <%= form.check_box :remote_ok %>
          <%= form.label :remote_ok, "Remote", class: "form-label" %>
          <section class="card-text">
            <div class="row">
              <% if @job.company_logo.attached? %>
                <div class="col-md-3">
                  <%= link_to delete_upload_job_url(@job, @job.company_logo.id), method: :delete, data: { confirm: 'Are you sure you want to delete this image?' }, class:"delete_image" do %>
                    <i class="fa fa-times">
                      <%= image_tag @job.company_logo.variant(resize_to_limit: [100, 100]), class: "mb-2" %>
                    </i>
                  <% end %>
                </div>
              <% end %>
              <div class="col">
                <%= form.file_field :company_logo, class: "form-control job-company-logo" %>
                <%= form.label :company_logo, "Company Logo", class: "form-label" %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <!-- Title input -->
                <div class="form-outline">
                  <%= form.text_field :title, class: "form-control", required: true %>
                  <%= form.label :title, class: "form-label" %>
                </div>
              </div>
              <div class="col">
                <!-- URL input -->
                <div class="form-outline">
                  <%= form.text_field :url, class: "form-control", required: true %>
                  <%= form.label :url, "Website", class: "form-label" %>
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <%= form.select( :job_type, options_for_select(Job::TYPES, @job.job_type), { :prompt => true }, required: true, class: "form-control") %>
                  <%= form.label :job_type, class: "form-label" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <%= form.select( :salary_range, options_for_select(Job::SALARY_RANGE, @job.salary_range), { :prompt => true }, required: true, class: "form-control" ) %>
                <%= form.label :salary_range, class: "form-label" %>
              </div>
              <div class="col">
                <%= form.date_field :start_date, required: true, class: "form-control" %>
                <%= form.label :start_date, class: "form-label" %>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <!-- Tag List -->
                <div class="form-outline">
                  <%= form.text_field :tag_list, placeholder: "Tags (separated by spaces)", class: "form-control", required: true %>
                  <%= form.label :tag_list, "Tags (Separated by spaces) | ", class: "form-label" %>
                  <% @job.most_used_tags.each do |tag| %>
                    <%= tag.name.capitalize %>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <%= form.select( :num_employees, options_for_select(Job::NUM_EMPLOYEES, @job.num_employees), { :prompt => true }, required: true, class: "form-control" ) %>
                <%= form.label :num_employees, "Employees", class: "form-label" %>
              </div>
              <div class="col">
                <%= form.select( :status, options_for_select(Job::STATUS, @job.status), { :prompt => true }, required: true, class: "form-control" ) %>
                <%= form.label :status, "Job status", class: "form-label" %>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <!-- Description -->
                <div class="form-outline">
                  <%= form.rich_text_area :description, class: "form-control customized-min-height", input_html: { rows: "10" }, required: true %>
                  <%= form.label :description, class: "form-label" %>
                </div>
              </div>
            </div>

           <div class="row">
           <div class="col-md-2 align-self-md-center text-center">
               <strong>Benefits</strong>
              </div>
              <div class="col-md-10">
                <% Job::BENEFITS.each_with_index do |benefit, index| %>
                  <div class="benefit d-inline-block p-2">
                    <%= form.check_box :benefits, { multiple: true, checked: form.object.benefits&.include?(benefit.to_s) }, benefit, nil %>
                    <%= form.label :benefits, benefit, class: "form-label" %>
                  </div>
                <% end %>
              </div>
            </div>

            <!--Images Uploads-->
            <div class="row mb-2 p-2">
              <div class="col">
                <% if @job.images.attached? %>
                  <% @job.images.each do |image| %>
                    <%= link_to delete_upload_job_url(@job, image.id), method: :delete, data: { confirm: 'Are you sure you want to delete this image?' }, class:"delete_image" do %>
                      <i class="fa fa-times">
                        <%= image_tag image.variant(resize_to_limit: [200, 200]), class: "mb-2" %>
                      </i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= form.file_field :images, multiple: true, class: "form-control job-images" %>
                <%= form.label :images, class: "form-label" %>
              </div>
            </div>

            <!-- Uppy Images Uploads-->

            <div class="row mb-3">
              <div class="col">
                <output id="list"></output>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <%= form.text_field :location, class: "form-control", required: true %>
                <%= form.label :location, class: "form-label" %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= form.text_field :apply_url, class: "form-control", required: true %>
                <%= form.label :apply_url, class: "form-label" %>
              </div>
              <div class="col">
                <%= form.text_field :job_author, class: "form-control", required: true %>
                <%= form.label :job_author, "Company Name", class: "form-label" %>
              </div>
              <div class="col">
                <%= form.select( :industry, options_for_select(Job::INDUSTRIES, @job.industry), { :prompt => true }, required: true, class: "form-control" ) %>
                <%= form.label :industry, class: "form-label" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%#= render 'payment' %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col">
              <%= form.submit "Save Job", class: "btn btn-primary save-btn-jobs" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col">
              <div class="back-btn-jobs p-2 text-center">
                <%= link_to 'Back', jobs_path, class: "btn-link back-btn-jobs" %>
              </div>
            </div>
            <% if (action_name == 'edit') %>
              <% if (current_user.id == @job.user_id) || (current_user.is_admin) %>
                <div class="col">
                  <div class="delete-btn-jobs p-2 text-center">
                    <%= link_to 'Delete', job_path(@job), :confirm => "Are you sure?", :method => :delete, class: "btn-link delete-btn-jobs" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
<% end %>

app/views/jobs/_infowindow.html.erb
<div class="row">
  <div class="col-md-12">


    <div class="card map-popup">
      <img
        src="https://mdbootstrap.com/img/new/standard/nature/184.jpg"
        class="card-img-top"
        alt="..."
        />
      <div class="card-body">
        <h5 class="card-title"><%= job.job_author %></h5>
        <p class="card-text">
          <h4><%= job.title %></h4>
          <% if job.remote_ok %>
            <h5>Remote</h5>
          <% end %>
        </p>
        <p>
          <%= link_to "Apply", "/jobs/#{job.id}", class: "btn btn-primary map-popup-btn" %>
        </p>
      </div>
    </div>


  </div>
</div>

app/views/jobs/_like_link.html.erb
<%= link_to "",
      like_job_path(job),
      method: :put,
      remote: true,
      class: "far fa-heart",
      style: 'text-decoration: none;'
%>

app/views/jobs/_likes.html.erb
<%= job.get_upvotes.size %>

app/views/jobs/_payment.html.erb
<% if !@job.persisted? %>
  <div class="row justify-content-center payment-title p-5 mt-4">
    <div class="row">
      <h4 class="subtitle mt-4">Payment</h4>
      <span><i class="fab fa-cc-stripe" style="font-size: 4em;"></i></span>
      <div class="notification is-light has-text-centered">
        All jobs cost <strong>$10</strong> USD for 30 days.
        <span class="block mb-4"></span>
      </div>
    </div>
  </div>


  <div class="form-row p-4 m-4">
    <label for="card-element" class="label">
      <i class="fa fa-credit-card"></i>
      Enter credit or debit card
    </label>

    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <% if current_user.stripe_id.present? %>
    <div class="last-card bg-light p-4 border-radius-3 m-4">
      <h5 class="is-6 title p-2">Previously used card</h5>
      <table class="table is-narrow bg-light is-fullwidth">
        <thead>
        <th>Card Brand</th>
        <th>Last 4 Digits</th>
        <th>Expiration Month</th>
        <th>Expiration Year</th>
        </thead>
        <tr>
          <td><%= current_user.card_brand %></td>
          <td><%= current_user.card_last4 %></td>
          <td><%= current_user.card_expiry_month %></td>
          <td><%= current_user.card_expiry_year %></td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>

app/views/jobs/edit.html.erb
<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
<div class="row m-2">
    <%= render partial: "shared/search_form" %>

    <div id="jobs">
      <% @jobs.each_slice(4) do |jobs| %>
        <div class="row">
          <% jobs.each do |job| %>
            <% if job.status == "Active" %>
              <div class="col">
                <div class="card p-0 mb-4">
                  <% if job.images.attached? %>
                    <%= link_to job do %>
                      <%= image_tag job.images.first, class: "card-img-top" %>
                    <% end %>
                  <% end %>
                  <div class="card-body">
                    <div class="row">
                      <div class="col">
                        <h1 class="card-company p-2" style="display: inline-block;">
                          <%= link_to job.job_author, job %>
                        </h1>
                        <% if job.company_logo.attached? %>
                            <%= image_tag job.company_logo.variant(resize_to_limit: [50, 50]), style: "float: left;" %>
                        <% end %>
                      </div>
                    </div>

                    <div class="row p-1">
                      <div class="col">
                        <h5 class="card-title"><%= link_to job.title, job %></h5>
                      </div>
                    </div>

                    <div class="row p-1">
                      <div class="col">
                        <h6><%= job.salary_range %></h6>
                      </div>
                    </div>

                    <div class="row p-1">
                      <div class="col">
                    <span class="parent-likes">
                      <span>
                      <i class="far fa-eye">
                        <%= job.impressionist_count %>
                      </i>
                      </span>
                      <br>
                      <span class="likes">
                        <i class="far fa-heart">
                          <%= job.get_upvotes.size %>
                        </i>
                      </span>
                    </span>
                      </div>
                    </div>

                    <p class="card-text">
                    <div class="show-jobs-description">
                      <%= job.description.to_plain_text.truncate(250) %>
                    </div>
                    <% job.tag_list.each do |tag| %>
                  <span class="show-tag-cloud float-start">
                    <%= link_to tag, tag_path(tag: tag) %>
                  </span>
                    <% end %>
                    </p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <% if job.remote_ok %>
                      <li class="list-group-item">
                        <i class="fas fa-laptop-house p-2">
                          <span>Remote</span>
                        </i>
                      </li>
                    <% end %>
                    <li class="list-group-item">
                      <i class="fas fa-file-contract p-2">
                        <%= job.job_type %>
                      </i>
                    </li>
                    <li class="list-group-item">
                      <i class="fas fa-map-marker-alt p-2">
                        <%= job.location %>
                      </i>
                    </li>
                    <li class="list-group-item">
                      <i class="fas fa-user p-2">
                        <%= job.user.username %>
                      </i>
                    </li>
                  </ul>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

</div>

app/views/jobs/like.js.erb
$('#like-count').html("<%= j render 'jobs/likes', job: @job %>");
$('#like-link').html("<%= j render 'jobs/like_link', job: @job %>");

app/views/jobs/my_jobs.html.erb
<div class="row m-2">

  <% @my_jobs.each_slice(4) do |jobs| %>
    <div class="row">
      <% jobs.each do |job| %>
        <div class="col">
          <div class="card p-0 mb-4">
            <%# binding.pry %>
            <% if job.images.attached? %>
              <%= link_to job do %>
                <%= image_tag job.images.first, class: "card-img-top" %>
              <% end %>
            <% end %>
            <div class="card-body">
              <h3 class="card-company"><%= job.job_author %></h3>
              <h5 class="card-title"><%= link_to job.title, job %></h5>
              <h6>Images: <%= job.images.count if job.images %></h6>
              <h6><%= job.salary_range %></h6>
              <p class="card-text">
              <div class="show-jobs-description">
                <%= job.description.to_plain_text.truncate(250) %>
              </div>
              <% job.tag_list.each do |tag| %>
                  <span class="show-tag-cloud float-start">
                    <%= link_to tag, tag_path(tag: tag) %>
                  </span>
              <% end %>
              </p>
            </div>
            <ul class="list-group list-group-flush">
              <% if job.remote_ok %>
                <li class="list-group-item">
                  <i class="fas fa-laptop-house p-2">
                    <span>Remote</span>
                  </i>
                </li>
              <% end %>
              <li class="list-group-item">
                <i class="fas fa-file-contract p-2">
                  <%= job.job_type %>
                </i>
              </li>
              <li class="list-group-item">
                <i class="fas fa-compass p-2">
                  <%= job.location %>
                </i>
              </li>
              <li class="list-group-item">
                <i class="fas fa-user p-2">
                  <%= job.user.username %>
                </i>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<div class="row m-4">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="card">
      <div class="col-md-12">
        <% if @job.images.attached? %>
          <div id="jobs-images" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% @job.images.each_with_index do |image, index| %>
                <% if index == 0 %>
                  <div class="carousel-item active" data-mdb-interval="2000">
                    <%= image_tag @job.images.first, class: "d-block w-100" %>
                  </div>
                <% else %>
                  <div class="carousel-item" data-mdb-interval="2000">
                    <%= image_tag image, class: "d-block w-100" %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#jobs-images" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#jobs-images" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col">
          <div id="show-map"
               data-jobs="<%= @geojson.to_json %>"
               data-mapbox-api-key="<%= Rails.application.credentials.dig(:mapbox, :public_api_key) %>">
          </div>
        </div>
      </div>

      <div class="row p-4">
        <div class="col-md-1">
          <span>Views: <%= @job.impressionist_count %></span>
        </div>
        <div class="col-md-1">
          <span class="parent-likes">
            <span id="like-link">
              <%= render 'jobs/like_link', job: @job %>
            </span>
            <span id="like-count" job-ib="<%= @job.id %>">
              <%= render 'jobs/likes', job: @job %>
            </span>
          </span>
        </div>
        <div class="col">
          <%= link_to "Apply Here", "#{@job.apply_url}", target: "_blank", class: 'btn-link show-apply-here' %>
        </div>
      </div>

      <div class="card-body">
        <div class="card-text">
          <div class="row">
            <% if @job.company_logo.attached? %>
              <div class="col-md-1 d-flex align-items-center">
                <span><%= image_tag @job.company_logo.variant(resize_to_limit: [50, 50]) %></span>
              </div>
            <% end %>
            <div class="col">
              <span class="show-job-author">
                <%= @job.job_author %>
              </span>
              <span class="show-website">
                <% job_url = @job.url.to_s %>
                <a href="<%= job_url %>" target="_blank">
                  <i class="fas fa-external-link-square-alt"></i>
                </a>
              </span>
            </div>
            <div class="row">
              
              <div class="col">

                <h1 class="mb-0" style="display: inline"><%= @job.title %></h1> | <h5 style="display: inline"><%= @job.industry %></h5>
                <h6><%= "Remote |" if @job.remote_ok %> <%= @job.location %></h6>
                <h6><%= @job.job_type.capitalize %></h6>
                <h6><%= @job.salary_range %></h6>
                <h6><strong>Start Date: </strong><%= @job.start_date.strftime("%B %d, %Y") %></h6>
                <h6><strong>Number of Employees: </strong><%= @job.num_employees %></h6>
                <div class="show-div-tag-cloud">
                  <% @job.tag_list.each do |tag| %>
                  <span class="show-tag-cloud">
                    <%= link_to tag, tag_path(tag: tag) %>
                  </span>
                  <% end %>
                </div>

              </div>
            </div>

            <div class="row">
              <div class="col-md-1"></div>
              <div class="col">

              </div>
            </div>

          </div>

          <div class="row">
            <div class="col">
              <div class="show-job-created">
                Posted: <%= @job.created_at.strftime("%B %d, %Y") %>
              </div>
              <br>
              <div class="show-job-created">
                Author: <%= @job.user.username %>
              </div>
            </div>
          </div>
          <hr>
          <p>
            <%= @job.description %>
          </p>
          <p>
            <% if @related_jobs %>
              <% @related_jobs.each do |r| %>
                <li><%= link_to r.title, r %></li>
              <% end %>
            <% end %>
          </p>
          <div class="row">
            <div class="col">
              <div class="back-btn-jobs p-2 text-center">
                <%= link_to 'Back', jobs_path, class: "btn-link back-btn-jobs" %>
              </div>
            </div>
            <% if current_user && current_user.id == @job.user_id %>
              <div class="col">
                <div class="edit-btn-jobs p-2 text-center">
                  <%= link_to 'Edit', edit_job_path(@job), class: "btn-link edit-btn-jobs" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-md-1"></div>
</div>