config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
    end
  end

  resources :companies
  root 'pages#home'

  get 'terms', to: 'pages#terms'
  get 'map', to: 'pages#map'
  get 'admin', to: 'pages#admin'

  resources :jobs do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
      put "like" => "jobs#like"
    end
  end
  get "my_jobs", to: 'jobs#my_jobs', as: :my_jobs
  get 'tags/:tag', to: 'jobs#index', as: :tag

  devise_for :users
end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_project,
                  against: [:title, :description],
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }

  # Project Tags
  acts_as_taggable_on :tags
  ActsAsTaggableOn.delimiter = ' '
  ActsAsTaggableOn.force_lowercase = true

  # LIKE / UNLIKE / VOTABLE
  acts_as_votable

  # Project Views / Impressions
  is_impressionable

  has_many_attached :images, service: :amazon
  has_rich_text :description

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  belongs_to :user

  def coordinates
    [longitude, latitude]
  end

  def to_feature
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": coordinates
      },
      "properties": {
        "project_id": id,
        "title": title,
        "description": description,
        "price": price,
        "location": location,
        "start_date": start_date,
        "end_date": end_date,
        "info_window": ApplicationController.new.render_to_string(
          partial: "projects/infowindow",
          locals: { project: self }
        )
      }
    }
  end

  def most_used_tags
    ActsAsTaggableOn::Tag.most_used(5)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy delete_upload ]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :js, :html, :json

  def index
    @projects = Project.all
    @tags = ActsAsTaggableOn::Tag.most_used(10).order("created_at DESC")
  end

  def show
    @related_projects = @project.find_related_tags
    @geojson = build_geojson
    impressionist(@project)
  end

  def new
    @user = current_user
    @project = @user.projects.build
  end

  def edit
  end

  def create
    @user = current_user
    @project = @user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_upload
    attachments = ActiveStorage::Attachment.where(id: params[:upload_id])
    attachments.map(&:purge)
    redirect_to edit_project_path(@project), notice: 'Image deleted.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(
        :title,
        :description,
        :start_date,
        :end_date,
        :search,
        :price,
        :location,
        :tag_list,
        images: []
      )
    end

    def build_geojson
      @project_feature = [@project]
      {
        type: "FeatureCollection",
        features: @project_feature.map(&:to_feature)
      }
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, html: { multipart: true }, local: true) do |form| %>
  <div class="row">
    <div class="col"></div>
    <div class="col-md-10">
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
  <div class="row m-4">
    <div class="col"></div>
    <div class="col-md-10">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title"><%= action_name.capitalize %> Project</h2>
          <div class="card-text">
            <div class="row">
              <div class="col">
                <!-- Title input -->
                <div class="form-outline">
                  <%= form.text_field :title, class: "form-control", required: true %>
                  <%= form.label :title, class: "form-label" %>
                </div>
              </div>
              <div class="col">
                <!-- URL input -->
                <div class="form-outline">
                  <%= form.number_field :price, class: "form-control", required: true %>
                  <%= form.label :price, "Price ($)", class: "form-label" %>
                </div>
              </div>
              <div class="col">
                <!-- URL input -->
                <div class="form-outline">
                  <%= form.text_field :location, class: "form-control", required: true %>
                  <%= form.label :location, "Location", class: "form-label" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <div class="form-outline">
                  <%= form.date_field :start_date, required: true, class: "form-control" %>
                  <%= form.label :start_date, class: "form-label" %>
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <%= form.date_field :end_date, required: true, class: "form-control" %>
                  <%= form.label :end_date, class: "form-label" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <!-- Tag List -->
                <div class="form-outline">
                  <%= form.text_field :tag_list, placeholder: "Tags (separated by spaces)", class: "form-control", required: true %>
                  <%= form.label :tag_list, "Tags (separated by spaces) ", class: "form-label" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <!-- Description -->
                <div class="form-outline">
                  <%= form.rich_text_area :description, class: "form-control customized-min-height", input_html: { rows: "10" }, required: true %>
                  <%= form.label :description, class: "form-label" %>
                </div>
              </div>
            </div>

            <div class="row mb-2 p-2">
              <div class="col">
                <% if @project.images.attached? %>
                  <% @project.images.each do |image| %>
                    <%= link_to delete_upload_project_url(@project, image.id), method: :delete, data: { confirm: 'Are you sure you want to delete this image?' }, class:"delete_image" do %>
                      <i class="fa fa-times">
                        <%= image_tag image.variant(resize_to_limit: [200, 200]), class: "mb-2" %>
                      </i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= form.file_field :images, multiple: true, direct_upload: true, class: "form-control job-images" %>
                <%= form.label :images, class: "form-label" %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col">
                <output id="list"></output>
              </div>
            </div>

          </div>

          <div class="row">
            <div class="col">
              <%#= render 'payment' %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col">
              <%= form.submit "Save Project", class: "btn btn-primary save-btn-jobs" %>
            </div>
          </div>


          <div class="row mb-2">
            <div class="col">
              <div class="back-btn-jobs p-2 text-center">
                <%= link_to 'Back', projects_path, class: "btn-link back-btn-jobs" %>
              </div>
            </div>
            <% if (action_name == 'edit') %>
              <% if (current_user.id == @project.user_id) || (current_user.is_admin) %>
                <div class="col">
                  <div class="delete-btn-jobs p-2 text-center">
                    <%= link_to 'Delete', project_path(@project), :confirm => "Are you sure?", :method => :delete, class: "btn-link delete-btn-jobs" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col"></div>
  </div>
<% end %>

app/views/projects/_infowindow.html.erb
<div class="row">
  <div class="col-md-12">


    <div class="card map-popup">
      <img
        src="https://mdbootstrap.com/img/new/standard/nature/184.jpg"
        class="card-img-top"
        alt="..."
        />
      <div class="card-body">
        <h5 class="card-title"><%= project.title %></h5>
        <p class="card-text">
        <h4><%= project.start_date.strftime("%d / %m / %Y") %></h4>
        </p>
        <p>
          <%= link_to "More Info", "/projects/#{project.id}", class: "btn btn-primary map-popup-btn" %>
        </p>
      </div>
    </div>


  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="row m-2">
  <%= render partial: "shared/project_search_form" %>

  <div id="projects">
    <% @projects.each_slice(4) do |projects| %>
      <div class="row">
        <% projects.each do |project| %>
            <div class="col">
              <div class="card p-0 mb-4">
                <% if project.images.attached? %>
                  <%= link_to project do %>
                    <%= image_tag project.images.first, class: "card-img-top" %>
                  <% end %>
                <% end %>
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h1 class="p-2 card-title"><%= link_to project.title, project %></h1>
                    </div>
                  </div>

                  <div class="row p-1">
                    <div class="col">
                    <span class="parent-likes">
                      <span>
                      <i class="far fa-eye">
                        <%= project.impressionist_count %>
                      </i>
                      </span>
                      <br>
                      <span class="likes">
                        <i class="far fa-heart">
                          <%= project.get_upvotes.size %>
                        </i>
                      </span>
                    </span>
                    </div>
                  </div>

                  <p class="card-text">
                  <div class="show-jobs-description">
                    <%= project.description.to_plain_text.truncate(250) %>
                  </div>
                  <% project.tag_list.each do |tag| %>
                  <span class="show-tag-cloud float-start">
                    <%= link_to tag, tag_path(tag: tag) %>
                  </span>
                  <% end %>
                  </p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    <i class="fas fa-file-contract p-2">
                      <%= project.start_date.strftime("%d / %m / %Y") %>
                    </i>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-map-marker-alt p-2">
                      <%= project.end_date.strftime("%d / %m / %Y") %>
                    </i>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-user p-2">
                      <%= project.user.username %>
                    </i>
                  </li>
                </ul>
              </div>
            </div>

        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="row m-4">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="card">
      <div class="col-md-12">
        <% if @project.images.attached? %>
          <div id="jobs-images" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% @project.images.each_with_index do |image, index| %>
                <% if index == 0 %>
                  <div class="carousel-item active" data-mdb-interval="2000">
                    <%= image_tag @project.images.first, class: "d-block w-100" %>
                  </div>
                <% else %>
                  <div class="carousel-item" data-mdb-interval="2000">
                    <%= image_tag image, class: "d-block w-100" %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#jobs-images" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#jobs-images" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col">
          <div id="show-map"
               data-jobs="<%= @geojson.to_json %>"
               data-mapbox-api-key="<%= ENV['MAPBOX_PUBLIC_API_KEY'] %>">
          </div>
        </div>
      </div>

      <div class="row p-4">
        <div class="col-md-1">
          <span>Views: <%= @project.impressionist_count %></span>
        </div>
        <div class="col-md-1">
          <span class="parent-likes">
            <span id="like-link">
              <%= render 'jobs/like_link', job: @project %>
            </span>
            <span id="like-count" job-ib="<%= @project.id %>">
              <%= render 'jobs/likes', job: @project %>
            </span>
          </span>
        </div>

      </div>

      <div class="card-body">
        <div class="card-text">
          <div class="row">

            <div class="row">
              <div class="col-md-1"></div>
              <div class="col">

                <h1 class="mb-0" style="display: inline"><%= @project.title %></h5>
                <h6><%= @project.location %></h6>
                <h6><strong>Start Date: </strong><%= @project.start_date.strftime("%B %d, %Y") %></h6>
                <h6><strong>End Date: </strong><%= @project.end_date.strftime("%B %d, %Y") %></h6>

                <div class="show-div-tag-cloud">
                  <% @project.tag_list.each do |tag| %>
                  <span class="show-tag-cloud">
                    <%= link_to tag, tag_path(tag: tag) %>
                  </span>
                  <% end %>
                </div>

              </div>
            </div>

            <div class="row">
              <div class="col-md-1"></div>
              <div class="col">

              </div>
            </div>

          </div>

          <div class="row">
            <div class="col">
              <div class="show-job-created">
                Posted: <%= @project.created_at.strftime("%B %d, %Y") %>
              </div>
              <br>
              <div class="show-job-created">
                Author: <%= @project.user.username %>
              </div>
            </div>
          </div>
          <hr>
          <p>
            <%= @project.description %>
          </p>
          <p>
            <% if @related_projects %>
              <% @related_projects.each do |r| %>
              <li><%= link_to r.title, r %></li>
            <% end %>
          <% end %>
          </p>
          <div class="row">
            <div class="col">
              <div class="back-btn-jobs p-2 text-center">
                <%= link_to 'Back', jobs_path, class: "btn-link back-btn-jobs" %>
              </div>
            </div>
            <% if current_user && current_user.id == @project.user_id %>
              <div class="col">
                <div class="edit-btn-jobs p-2 text-center">
                  <%= link_to 'Edit', edit_project_path(@project), class: "btn-link edit-btn-jobs" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-md-1"></div>
</div>