config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
    end
  end

  resources :companies
  root 'pages#home'

  get 'terms', to: 'pages#terms'
  get 'map', to: 'pages#map'
  get 'admin', to: 'pages#admin'

  resources :jobs do
    member do
      delete "delete_upload/:upload_id", action: :delete_upload, as: :delete_upload
      put "like" => "jobs#like"
    end
  end
  get "my_jobs", to: 'jobs#my_jobs', as: :my_jobs
  get 'tags/:tag', to: 'jobs#index', as: :tag

  devise_for :users
end

app/views/layouts/_messages.html.erb
<div class="notifications text-center">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= type.capitalize %>: <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to "Solos", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_page?(jobs_path) %>
            <%= link_to "Jobs", jobs_path, class: "nav-link active", "aria-current" => "jobs" %>
          <% else %>
            <%= link_to "Jobs", jobs_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(projects_path) %>
            <%= link_to "Projects", projects_path, class: "nav-link active", "aria-current" => "projects" %>
          <% else %>
            <%= link_to "Projects", projects_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(companies_path) %>
            <%= link_to "Companies", companies_path, class: "nav-link active", "aria-current" => "companies" %>
          <% else %>
            <%= link_to "Companies", companies_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(map_path) %>
            <%= link_to "Map", map_path, class: "nav-link active", "aria-current" => "map" %>
          <% else %>
            <%= link_to "Map", map_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item p-1">
            <%= link_to "+ Job", new_job_path, class: "nav-link post-job-btn", "aria-current" => "page" %>
          </li>
          <li class="nav-item p-1">
            <%= link_to '+ Project', new_project_path, class: "nav-link post-project-btn", "aria-current" => "page" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to current_user.username, edit_user_registration_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to "My Jobs", my_jobs_path, class: 'dropdown-item' %>
              </li>
              <li>
                <% if current_user.is_admin %>
                  <%= link_to "Admin", admin_path, class: 'dropdown-item' %>
                <% end %>
              </li>
              <li>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'Terms of Service', terms_path, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Terms of Service', terms_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'stripe', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>

    <!-- Stripe -->
    <%= tag :meta, name: "stripe-public-key", content: Rails.application.credentials.dig(:stripe, :access_key) %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container-fluid jobworks-container">
      <%= yield %>
    </div>
  </body>
</html>